spring:
  profile:
    active: ${PROFILE}
  application:
    name: Enterprise

  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:password}

  jpa:
    database: ${JPA_DATABASE:H2}
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: ${JPA_DIALECT:org.hibernate.dialect.H2Dialect}
        format_sql: true
    show-sql: true
  mvc:
    format:
      date-time: iso

  liquibase:
    enabled: true
    change-log: "classpath:/liquibase/changelog-master.yaml"

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:5242880}
      max-request-size: ${MAX_REQUEST_SIZE:10485760}

server:
  port: ${SERVER_PORT:8080}

debug: false

logging:
  level:
    liquibase: INFO
    org:
      springframework: INFO
    com:
      knits:
        enterprise: DEBUG
